version: '3'
services:
  telegrambot:
    build: telegrambot
    restart: unless-stopped
    depends_on:
      - "mongodb"
    networks:
      - defaultnet
  backend:
    build: backend
    restart: unless-stopped
    depends_on:
      - "mongodb"
    networks:
      - defaultnet
    ports:
      - "3000:3000"
  nlp:
    build: nlp
    restart: unless-stopped
    depends_on:
      - "mongodb"
    networks:
      - defaultnet
  mongodb:
    image: mongo:4.0.4
    restart: unless-stopped
    networks:
      - defaultnet
networks:
  defaultnet:
    driver: bridge